<a href="https://colab.research.google.com/github/ASO1801033/AI_teach2020/blob/master/20201009AI0205_selectAlgo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## sklearnでエラーが出るので、前のバージョンを入れ直す

In [40]:
# 現在のscikit-learnをVMからアンインストール
# !pip uninstall scikit-learn
# 前のバージョンを指定してVMにインストール
# !pip install scikit-learn==0.20 --ignore-installed

## all_estimators()でループして各種のアルゴリズムで学習させ、比較する

In [41]:
# ライブラリの読み込み
import pandas as pd
# 学習用データとテスト検証用データを分割するライブラリ
from sklearn.model_selection import train_test_split
# 正解率を算出するライブラリ
from sklearn.metrics import accuracy_score
# all_estimators(推論気の全てを利用できるようにする)
from sklearn.utils.testing import all_estimators
# 警告クラス
import warnings

## webからアヤメのデータを読み込む

In [42]:
# urlリンクから読み込むライブラリ
import urllib.request as req
# url用の文字列変数を定義
url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/pandas/tests/io/data/csv/iris.csv"
# リンクから保存するためのファイル名を定義
savefile = "iris.csv"
# requestクラスを使ってurlからデータをsavefileへコピーして保存
req.urlretrieve(url, savefile)
# pandasのread_csvメソッドを使ってCSVファイルを読み込む
iris_data = pd.read_csv(savefile, encoding="utf-8")
iris_data.head()

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

## アヤメデータを目的変数：y（ラベル）と説明変数：x（入力データ）に分離する

In [43]:
y = iris_data.loc[:, "Name"] # 目的変数
x = iris_data.loc[:, ["SepalLength", "SepalWidth", "PetalLength", "PetalWidth"]] # 説明変数

print(y.head())
print(x.head())

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Name, dtype: object
   SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2


## アヤメデータをさらに学習用とテスト検証用に分離する

In [44]:
# 学習用データ（train）とテスト検証用データ（test）に分離
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, train_size=0.8, shuffle=True)
print(x_train.head())
print(y_train.head())
print(x_test.head())
print(y_test.head())

     SepalLength  SepalWidth  PetalLength  PetalWidth
19           5.1         3.8          1.5         0.3
33           5.5         4.2          1.4         0.2
107          7.3         2.9          6.3         1.8
45           4.8         3.0          1.4         0.3
12           4.8         3.0          1.4         0.1
19        Iris-setosa
33        Iris-setosa
107    Iris-virginica
45        Iris-setosa
12        Iris-setosa
Name: Name, dtype: object
     SepalLength  SepalWidth  PetalLength  PetalWidth
9            4.9         3.1          1.5         0.1
134          6.1         2.6          5.6         1.4
59           5.2         2.7          3.9         1.4
38           4.4         3.0          1.3         0.2
15           5.7         4.4          1.5         0.4
9          Iris-setosa
134     Iris-virginica
59     Iris-versicolor
38         Iris-setosa
15         Iris-setosa
Name: Name, dtype: object


### allAlgorithmsにclassifierを指定して「分類」でフィルターしたアルゴリズム推定器群を取得する

In [45]:
# 推定器のリストをフィルター指定して取得
allAlgorithms = all_estimators(type_filter="classifier")
# ワーニングを無視する
warnings.filterwarnings('ignore')

## scikit-learnでエラーが出るのはデータがアルゴリズムに適していないのを判別してくれているから→エラーをキャッチしてみる

In [46]:
# 推定器のリストをループ
for (name, algorithm) in allAlgorithms:
  # pythonでのtry-catch(try-except)
  try: # pythonのtry
    # 各アルゴリズムのオブジェクトを生成
    clf = algorithm() # 各アルゴリズムクラスのコンストラクタを実行
    # 学習させる（fitメソッド）
    clf.fit(x_train, y_train)
    # 推論する
    y_pred = clf.predict(x_test)
    # accuracy_scoreで正解率を算出して表示
    print(name, "の正解率 = ", accuracy_score(y_test, y_pred))
  # tryの終わり
  # pythonのcatch(except)
  except Exception as e:
    print("\033[31m", "Error: \033[0m", name, ":", e.args) # \はバックスラッシュのエスケープ
    # pass
  else:
    # print("Exception以外、正常系など")
    pass
  # try-catch終了
# for文終了

AdaBoostClassifier の正解率 =  0.9333333333333333
BaggingClassifier の正解率 =  0.9666666666666667
BernoulliNB の正解率 =  0.3
CalibratedClassifierCV の正解率 =  0.9333333333333333
CategoricalNB の正解率 =  0.9333333333333333
 Error:  CheckingClassifier : ("could not convert string to float: 'Iris-setosa'",)
 Error:  ClassifierChain : ("__init__() missing 1 required positional argument: 'base_estimator'",)
ComplementNB の正解率 =  0.7
DecisionTreeClassifier の正解率 =  0.9666666666666667
DummyClassifier の正解率 =  0.36666666666666664
ExtraTreeClassifier の正解率 =  0.9
ExtraTreesClassifier の正解率 =  0.9666666666666667
GaussianNB の正解率 =  0.9333333333333333
GaussianProcessClassifier の正解率 =  0.9666666666666667
GradientBoostingClassifier の正解率 =  0.9666666666666667
HistGradientBoostingClassifier の正解率 =  0.9666666666666667
KNeighborsClassifier の正解率 =  0.9666666666666667
LabelPropagation の正解率 =  0.9666666666666667
LabelSpreading の正解率 =  0.9666666666666667
LinearDiscriminantAnalysis の正解率 =  1.0
LinearSVC の正解率 =  1.0
LogisticRegre

## クロスバリデーション

### クロスバリデーション関連のライブラリのインポート

In [47]:
# ライブラリのインポート
# K分割クロスバリデーション（交差検証）のためのライブラリ
from sklearn.model_selection import  KFold
# クロスバリデーションスコアを取得するためのオブジェクト
from sklearn.model_selection import  cross_val_score

### クロスバリデーションを実行する

In [48]:
# K分割交差検証用のインスタンスを生成する
kfold_cv = KFold(n_splits=5, shuffle=True)
# 既に生成してあるall_estimatorsのインスタンスをループさせて、クロスバリデーションを行う
for(name, algorithm) in allAlgorithms:
  try:
    # 各アルゴリズムのインスタンスを取得
    clf =  algorithm()
    # scoreの属性がある学習だけに絞る
    if hasattr(clf, "score"):
      # クロスバリデーションをしてスコアを取得する
      scores = cross_val_score(clf, x, y, cv=kfold_cv)
      # k=n_splits=5 回分のクロスバリデーションのスコアを表示
      print(name, "の正解率 = ")
      print(scores)
    # ifの終了
  # tryブロックの終了
  except: # 例外処理のブロック
    # 何もしない
    pass

AdaBoostClassifier の正解率 = 
[0.96666667 0.96666667 0.9        0.93333333 0.9       ]
BaggingClassifier の正解率 = 
[0.96666667 0.93333333 1.         0.96666667 0.83333333]
BernoulliNB の正解率 = 
[0.23333333 0.23333333 0.2        0.3        0.3       ]
CalibratedClassifierCV の正解率 = 
[0.93333333 0.93333333 0.9        0.9        0.86666667]
CategoricalNB の正解率 = 
[0.9        0.96666667 0.86666667 0.93333333 0.96666667]
CheckingClassifier の正解率 = 
[nan nan nan nan nan]
ComplementNB の正解率 = 
[0.7        0.63333333 0.53333333 0.73333333 0.73333333]
DecisionTreeClassifier の正解率 = 
[0.83333333 0.9        1.         0.96666667 0.96666667]
DummyClassifier の正解率 = 
[0.2        0.5        0.43333333 0.3        0.2       ]
ExtraTreeClassifier の正解率 = 
[0.93333333 0.76666667 0.86666667 0.96666667 0.93333333]
ExtraTreesClassifier の正解率 = 
[0.96666667 1.         0.93333333 0.96666667 0.9       ]
GaussianNB の正解率 = 
[0.96666667 1.         0.9        0.93333333 1.        ]
GaussianProcessClassifier の正解率 = 
[0.9        

### おまけ：もっと詳しい結果を取得できる新しいクロスバリデーションオブジェクト：cross_validate

In [49]:
# ライブラリのインポート
from sklearn.model_selection import cross_validate

### cross_validateを使ったクロスバリデーション

In [50]:
# K分割交差検証用のインスタンスを生成する
kfold_cv = KFold(n_splits=5, shuffle=True)
# 既に生成してあるall_estimatorsのインスタンスをループさせて、クロスバリデーションを行う
for(name, algorithm) in allAlgorithms:
  try:
    # 各アルゴリズムのインスタンスを取得
    clf =  algorithm()
    # scoreの属性がある学習だけに絞る
    if hasattr(clf, "score"):
      # cross_validateでクロスバリデーションをしてスコアを取得する
      scores = cross_validate(clf, x, y, cv=kfold_cv)
      # k=n_splits=5 回分のクロスバリデーションのスコアを表示
      print(name, "の正解率 = ")
      print(scores)
    # ifの終了
  # tryブロックの終了
  except: # 例外処理のブロック
    # 何もしない
    pass

AdaBoostClassifier の正解率 = 
{'fit_time': array([0.07316542, 0.06649351, 0.07189417, 0.0714519 , 0.06680107]), 'score_time': array([0.00821924, 0.00691915, 0.00826526, 0.00695443, 0.00695872]), 'test_score': array([1.        , 0.96666667, 0.93333333, 0.93333333, 0.9       ])}
BaggingClassifier の正解率 = 
{'fit_time': array([0.01568365, 0.01397276, 0.01411295, 0.01390052, 0.01397395]), 'score_time': array([0.00211072, 0.00200248, 0.0021162 , 0.00205874, 0.00204444]), 'test_score': array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 0.93333333])}
BernoulliNB の正解率 = 
{'fit_time': array([0.00289488, 0.00250268, 0.00249887, 0.00250316, 0.0024538 ]), 'score_time': array([0.00133562, 0.00119734, 0.0013752 , 0.00136471, 0.00119042]), 'test_score': array([0.23333333, 0.26666667, 0.2       , 0.26666667, 0.23333333])}
CalibratedClassifierCV の正解率 = 
{'fit_time': array([0.06245494, 0.06268024, 0.06198478, 0.05861497, 0.06028605]), 'score_time': array([0.00194716, 0.00218368, 0.00198174, 0.00196052, 0

## グリッドサーチで最適なパラメータを探し求める

### ライブラリをimport

In [51]:
# グリッドサーチのオブジェクトクラスをimport
from sklearn.model_selection import GridSearchCV
# SVCアルゴリズムの学習モデルをimport
from sklearn.svm import SVC

### グリッドサーチを実行してパラメータを試す

In [52]:
# グリッドサーチで試すパラメータのパターン指定を定義する
parameters = [
              # 3つのパラメータ、3パターン
              { "C":[1, 10, 100, 1000], "kernel":["linear"] },
              { "C":[1, 10, 100, 1000], "kernel":["rbf"], "gamma":[0.001, 0.0001] },
              { "C":[1, 10, 100, 1000], "kernel":["sigmoid"], "gamma":[0.001, 0.0001] }
]

# 普通の学習
clf_svc = SVC()
clf_svc.fit(x_train, y_train)
y_pred_svc = clf_svc.predict(x_test)
print("普通の学習の正解率 = ", accuracy_score(y_test, y_pred))

# グリッドサーチを行う
# K分割交差検証用のインスタンスを生成する
kfold_cv = KFold(n_splits=5, shuffle=True)
# グリッドサーチの中でK分割交差検証も行われる
clf_grid = GridSearchCV(SVC(), parameters, cv=kfold_cv) # インスタンス
clf_grid.fit(x_train, y_train) # 学習
# 学習済みモデルに最終的に設定された（最適と思われる）パラメータを表示
print("最適なパラメータ = ", clf_grid.best_estimator_)

# 最適なパラメータ設定済みの学習モデルで評価
y_pred_grid = clf_grid.predict(x_test)
print("グリッドサーチの正解率 = ", accuracy_score(y_test, y_pred))

普通の学習の正解率 =  0.9666666666666667
最適なパラメータ =  SVC(C=1000, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
グリッドサーチの正解率 =  0.9666666666666667


## Numpyの動作確認

In [53]:
# import
import numpy as np

In [55]:
# numpy配列の初期化
a = np.array([1, 2, 3, 4, 5]) # ndarrayというnumpy配列オブジェクトを生成
print(a)
# type関数で型を表示
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [58]:
# 2次元のndarrayを定義
b = np.array([ [1, 2, 3], [4, 5, 6] ])
print(b)

[[1 2 3]
 [4 5 6]]


In [62]:
# 配列の要素数を指定して0埋めで初期化
print(np.zeros(10))
print(np.zeros((3, 2)))
print(np.ones(2))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 1.]


In [68]:
# 連番の配列を要素数を指定して初期化
print(np.arange(5)) # 0から5未満
print(np.arange(2, 9)) # 2から9未満
print(np.arange(5, 8, 0.5)) # 5から8未満、0.5刻み

[0 1 2 3 4]
[2 3 4 5 6 7 8]
[5.  5.5 6.  6.5 7.  7.5]


### numpyで行列計算

In [77]:
a = np.array([1, 2, 3, 4, 5])
b = a * 2 # 全ての要素を一度に2倍
print(b)
x = np.arange(10)
print(x)
y = x * 3 + 5 # 全ての要素に一度に四則演算
print(y)

[ 2  4  6  8 10]
[0 1 2 3 4 5 6 7 8 9]
[ 5  8 11 14 17 20 23 26 29 32]


In [82]:
# 配列の次元数を表示
a = np.array([ [1, 2, 3], [4, 5, 6] ])
print("配列：aの中身と次元数")
print(a)
print(a.shape)
print()

print("配列：bの中身と次元数")
b = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
print(b)
print(b.shape)

配列：aの中身と次元数
[[1 2 3]
 [4 5 6]]
(2, 3)

配列：bの中身と次元数
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [90]:
# Numpy配列で次元数を変換する
a = np.array([ [1, 2, 3], [4, 5, 6] ])
print("a = ", a)
print()

b = a.flatten() # フラットにする（1次元配列にする）
print("b = ", b)
print()

a = np.array([ [1, 2, 3], [4, 5, 6] ]) # 2行3列
print(a)
print()

b = a.reshape(3, 2) # 3行2列に変換（回転）させる
print(b)

a =  [[1 2 3]
 [4 5 6]]

b =  [1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]


### numpyの配列にアクセスする方法

In [99]:
v = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
a = v[0]
print(a) # 2次元配列の0行目
print()

b = v[1:]
print(b) # 1行目以降
print()

c = v[:, 0]
print(c) # 全ての行の0列目

[1 2 3]

[[4 5 6]
 [7 8 9]]

[1 4 7]
